export interface MenuItem {
  id: string
  name: string
  description: string
  price: string
  image?: string
  allergens?: number[]
  subItems?: Array<{
    name: string
    price: string
  }>
  notAvailableOnline?: boolean
  notAvailableForDelivery?: boolean
}

export interface PackageGroup {
  packageId: string
  packageName: string
  packagePrice: string
  packageDescription?: string
  packageImage?: string
  categories: Array<{
    categoryName: string
    items: MenuItem[]
    notes?: string
  }>
}

export interface MenuCategory {
  id: string
  sectionTitle: string
  isPackageSection?: boolean
  packages?: PackageGroup[]
  categories: Array<{
    categoryName: string
    items: MenuItem[]
    notes?: string
  }>
}

export const menuData: MenuCategory[] = [
  {
    id: "breakfast-streetfood",
    sectionTitle: "ALL DAY BREAKFAST & STREETFOOD",
    categories: [
      {
        categoryName: "ALL DAY BREAKFAST & STREETFOOD",
        notes: "Pozycje 1-3 dostępne wyłącznie na miejscu w weekendy 10:00–13:00. Pozycje 4-9 dostępne również online.",
        items: [
          {
            id: "szakszuka-kofta",
            name: "Szakszuka z Grillowaną Koftą Jagnięcą / Shakshuka with Grilled Lamb Kofta",
            description: "Pomidory, cebula, czosnek, sumak, zatar, pikle, labneh, jajka, kofta jagnięca, serwowana z wypiekaną na miejscu pitą",
            price: "46 zł",
            image: "/images/menu/shakshuka-lamb-kofta-premium.jpeg",
            allergens: [1, 3, 7, 10, 11],
            notAvailableOnline: true,
          },
          {
            id: "szakszuka-falafel",
            name: "Szakszuka z Falafelem / Shakshuka with Falafel",
            description: "Pomidory, cebula, czosnek, sumak, zatar, pikle, labneh, jajka, falafel, serwowana z wypiekaną na miejscu pitą",
            price: "34 zł",
            image: "/images/menu/shakshuka-falafel-breakfast-updated.jpeg",
            allergens: [1, 3, 7, 10, 11],
            notAvailableOnline: true,
          },
          {
            id: "turkish-eggs",
            name: "Jajka po Turecku / Turkish Eggs",
            description: "Jajka, labneh, palone masło, sos zhoug, harissa, ciecierzyca, serwowane z wypiekanej na miejscu picie",
            price: "42 zł",
            image: "/images/menu/turkish-eggs-breakfast-updated.jpeg",
            allergens: [1, 3, 7, 10, 11],
            notAvailableOnline: true,
          },
          {
            id: "sabich",
            name: "Sabich",
            description: "Grillowany bakłażan, jajko, świeże warzywa, hummus, pietruszka, mięta, sosy: harissa i amba, podane na wypiekanej na miejscu picie",
            price: "42 zł",
            image: "/images/menu/sabich-new.webp",
            allergens: [1, 3, 7, 10, 11],
          },
          {
            id: "mezze-morning",
            name: "Mezze Morning",
            description: "2 x falafel, 2 x dowolne mezze do wyboru, pita",
            price: "29 zł",
            image: "/images/menu/talerz-basma-new.webp",
            allergens: [1, 7, 11],
          },
          {
            id: "wrap-syryjski",
            name: "Syryjski / Syrian Wrap",
            description: "Falafel, sałata, ogórek, pomidor, natka pietruszki, piklowana marchewka, sos basma",
            price: "29 zł",
            image: "/images/menu/wrap-syryjski-new.jpeg",
            allergens: [1, 11],
          },
          {
            id: "wrap-libanski",
            name: "Libański / Lebanese Wrap",
            description: "Kurczak taouk, sałata, papryka, pepperoni, płatki chilli, natka pietruszki, sos basma",
            price: "36 zł",
            image: "/images/menu/wrap-libanski-new.webp",
            allergens: [1, 7],
          },
          {
            id: "wrap-turecki",
            name: "Turecki / Turkish Wrap",
            description: "Adana kebab, sałata, cebula, pikle, sumak, natka pietruszki, sos toum, sos harissa",
            price: "39 zł",
            image: "/images/menu/wrap-turkish.jpeg",
            allergens: [1, 3, 10],
          },
          {
            id: "wrap-perski",
            name: "Perski / Persian Wrap",
            description: "Kofta jagnięca, ubijana feta, sałata, pikle, natka pietruszki",
            price: "44 zł",
            image: "/images/menu/wrap-perski-new.jpeg",
            allergens: [1, 7],
          },
        ],
      },
    ],
  },
  {
    id: "mezze-talerzyki",
    sectionTitle: "Talerzyki Mezze",
    categories: [
      {
        categoryName: "Małe Talerzyki",
        items: [
          {
            id: "falafel",
            name: "Falafel",
            description: "Smażona kulka z ciecierzycy z przyprawami",
            price: "5 zł",
            image: "/images/menu/falafel-mezze.jpeg",
            allergens: [11],
          },
          {
            id: "hummus-classic",
            name: "Hummus",
            description: "Pasta z ciecierzycy i masła sezamowego z przyprawami",
            price: "6 zł",
            image: "/images/menu/humus-new.webp",
            allergens: [11],
          },
          {
            id: "hummus-white-bean",
            name: "Hummus z Białej Fasoli",
            description: "Pasta z białej fasoli i masła sezamowego z przyprawami",
            price: "6 zł",
            image: "/images/menu/hummus-white-bean.jpg",
            allergens: [7, 11],
          },
          {
            id: "tzatziki",
            name: "Tzatziki",
            description: "Gęsty jogurt z ogórkiem i czosnkiem",
            price: "7 zł",
            image: "/images/menu/tzatziki-mezze.jpeg",
            allergens: [7],
          },
          {
            id: "labneh",
            name: "Labneh",
            description: "Kremowy serek z dodatkiem konfitowanego czosnku, oliwy i zataru",
            price: "7 zł",
            image: "/images/menu/labneh-mezze.jpeg",
            allergens: [7, 11],
          },
          {
            id: "mix-pikli",
            name: "Mix Pikli",
            description: "Chrupiące warzywa w aromatycznej zalewie octowej",
            price: "8 zł",
            image: "/images/menu/mixed-pickles-mezze.jpeg",
            allergens: [10, 12],
          },
          {
            id: "labneh-mietowy",
            name: "Labneh Miętowy",
            description: "Kremowy serek z dodatkiem mięty i natki pietruszki",
            price: "8 zł",
            image: "/images/menu/labneh-mietowy.jpg",
            allergens: [7],
          },
          {
            id: "labneh-sweet",
            name: "Labneh na Słodko",
            description: "Kremowy serek z dodatkiem miodu i pistacji",
            price: "9 zł",
            image: "/images/menu/sweet-labneh-new.jpeg",
            allergens: [7, 8, 11],
          },
          {
            id: "labneh-basma",
            name: "Labneh by BASMA",
            description: "Kremowy serek z konfitowanym czosnkiem, natką pietruszki i prażonym sezamem",
            price: "9 zł",
            image: "/images/menu/labneh-by-basma-new.webp",
            allergens: [7, 11],
          },
          {
            id: "tabbouleh",
            name: "Tabbouleh",
            description: "Sałatka z kaszą bulgur, pietruszką, miętą, koperkiem, ogórkiem i czerwoną cebulą",
            price: "9 zł",
            image: "/images/menu/tabbouleh-new.webp",
            allergens: [1, 10],
          },
          {
            id: "kibbeh",
            name: "Kibbeh",
            description: "Smażona kulka z kaszy bulgur z jagnięciną, cebulą i przyprawami",
            price: "10 zł",
            image: "/images/menu/kibbeh.jpg",
            allergens: [1, 8],
          },
          {
            id: "grilled-pepper-labneh",
            name: "Grillowana Papryka na Labneh",
            description: "Grillowana papryka podana na labneh",
            price: "11 zł",
            image: "/images/menu/grilled-pepper-labneh.jpg",
            allergens: [7, 11],
          },
          {
            id: "marinated-olives",
            name: "Marynowane Oliwki",
            description: "Z sumakiem, kiszoną cytryną, zatarem i sezamem",
            price: "11 zł",
            image: "/images/menu/marinated-olives-mezze.jpeg",
            allergens: [11],
          },
          {
            id: "tomatoes-amba",
            name: "Pomidory z sosem amba",
            description: "Pomidory z aromatycznym sosem amba",
            price: "12 zł",
            image: "/images/menu/tomatoes-amba.jpg", // Kept exact original filename or fallback
            allergens: [11],
          },
          {
            id: "muhammara",
            name: "Muhammara",
            description: "Pasta z pieczonej papryki, melasy z granatu i orzechów włoskich",
            price: "12 zł",
            image: "/images/menu/muhammara-mezze.jpeg",
            allergens: [8],
          },
          {
            id: "baba-ganoush",
            name: "Baba Ghanoush",
            description: "Pasta z pieczonego bakłażana z jogurtem, sumakiem, pastą sezamową i granatem",
            price: "13 zł",
            image: "/images/menu/baba-ganoush-mezze.jpeg",
            allergens: [7, 11],
          },
          {
            id: "ubijana-feta",
            name: "Ubijana Feta",
            description: "Pasta z serem feta, jogurtem greckim, czosnkiem, cytryną i słodką papryką",
            price: "13 zł",
            image: "/images/menu/whipped-feta-mezze.jpeg",
            allergens: [7],
          },
          {
            id: "grilled-corn-labneh",
            name: "Grillowana kukurydza na labneh z masłem chilli / Grilled Corn",
            description: "Grillowana kukurydza serwowana na kremowym labneh z pikantnym masłem chilli",
            price: "18 zł",
            image: "/images/menu/grillowana-kukurydza-new.webp",
            allergens: [7],
            notAvailableOnline: true,
          },
          {
            id: "all-mezze-set",
            name: "Menu degustacyjne / Mezze Tasting Menu",
            description: "Zestaw wszystkich mezze z 4x kibbeh i 4x falafel",
            price: "159 zł",
            allergens: [1, 4, 7, 8, 10, 11],
            notAvailableOnline: true,
          },
        ],
      },
    ],
  },
  {
    id: "mezze-talerze",
    sectionTitle: "Talerze Mezze",
    categories: [
      {
        categoryName: "Duże Talerze",
        items: [
          {
            id: "basma-talerz",
            name: "Basma",
            description: "3x falafel, hummus, labneh, grillowany bakłażan, mix pikli, pita",
            price: "39 zł",
            image: "/images/menu/talerz-basma-new.webp",
            allergens: [1, 7, 10, 11, 12],
          },
          {
            id: "libanski-talerz",
            name: "Libański / Lebanese",
            description: "2x Kibbeh, Hummus z białej fasoli, tabbouleh, grillowana papryka na labneh, mix pikli, pita",
            price: "42 zł",
            image: "/images/menu/talerz-libanski-new.webp",
            allergens: [1, 3, 7, 8, 10, 11, 12],
          },
          {
            id: "grecki-talerz",
            name: "Grecki / Greek",
            description: "2x falafel, grillowany bakłażan, oliwki, tzatziki, ubita feta, mix pikli, pita",
            price: "45 zł",
            image: "/images/menu/mezze-platter-greek.jpeg",
            allergens: [1, 7, 10, 11, 12],
          },
          {
            id: "arabski-talerz",
            name: "Arabski / Arabic",
            description: "2x falafel, hummus, labneh, tabbouleh, muhammara, mix pikli, pita",
            price: "39 zł",
            image: "/images/menu/arabski-new.jpeg",
            allergens: [1, 7, 10, 11, 12],
          },
          {
            id: "jerozolimski-talerz",
            name: "Jerozolimski / Jerusalem",
            description: "3 Falafels, Baba Ghanoush, Hummus, Muhammara, Pomidory z sosem amba, Pita",
            price: "45 zł",
            image: "/images/menu/talerz-jerozolimski-new.webp",
            allergens: [1, 7, 8, 10, 11, 12],
          },
          {
            id: "weganski-talerz",
            name: "Wegański / Vegan",
            description: "3x falafel, hummus, tabbouleh, muhammara, mix pikli, pita",
            price: "39 zł",
            image: "/images/menu/weganski-new.jpeg",
            allergens: [1, 8, 10, 11, 12],
          },
        ],
      },
    ],
  },
  {
    id: "grill",
    sectionTitle: "Dania z Grilla",
    categories: [
      {
        categoryName: "Mięsa z Grilla",
        items: [
          {
            id: "chicken-joojeh",
            name: "Kurczak Shish Joojeh / Shish joojeh chicken",
            description: "cytrynowy szaszłyk z kurczaka z szafranem i sosem zhoug",
            price: "39 zł",
            image: "/images/menu/kurczak-joojeh.jpg",
            allergens: [7, 10],
          },
          {
            id: "caramel-chicken",
            name: "Karmelowy Kurczak by BASMA / Caramel Chicken by basma",
            description: "Słodko-pikantny kurczak z wodą pomarańczową i orzechową dukkah",
            price: "39 zł",
            image: "/images/menu/kurczak-karmelowy-new.webp",
            allergens: [8, 11],
          },
          {
            id: "chicken-taouk",
            name: "Kurczak Shish Taouk / Shish Taouk Chicken",
            description: "Aromatyczny szaszłyk z kurczaka z harissą",
            price: "39 zł",
            image: "/images/menu/kurczak-taouk.jpg",
            allergens: [7, 10],
          },
          {
            id: "chicken-shish-shawarma",
            name: "Chicken Shish shawarma",
            description: "Chicken Skewers Marinated in Yogurt and Shawarma Spices, Served With Amba Sauce And Arabic Yogurt Relish",
            price: "39 zł",
            image: "/images/menu/shish-shawarma-new.webp",
            allergens: [7, 11],
          },
          {
            id: "fiery-wings",
            name: "Fiery Wings By basma",
            description: "Spicy harissa chicken wings with chili flakes, honey, and lime juice",
            price: "39 zł",
            image: "/images/menu/explorer-plate.jpg",
            allergens: [3, 7, 10],
          },
          {
            id: "sweet-sour-wings",
            name: "Marinated sweet & sour wings",
            description: "Honey and pomegranate molasses chicken wings with sumac and urfa biber flakes",
            price: "39 zł",
            image: "/images/menu/explorer-plate.jpg",
            allergens: [3, 7, 11],
          },
          {
            id: "adana-kebap",
            name: "Adana Kebap Barani / Adana Mutton Kebap",
            description: "with toum and harissa sauces, pickles and parsley",
            price: "49 zł",
            image: "/images/menu/adana-new.webp",
            allergens: [3, 10, 12],
          },
          {
            id: "kofty-jagniece",
            name: "Kofty Jagnięce / Lamb Koftas",
            description: "Z sosami zhoug i harissa, piklami, natką pietruszki i cebulą z sumakiem",
            price: "59 zł",
            image: "/images/menu/kofta-new.webp",
            allergens: [7, 10, 12],
          },
          {
            id: "meat-platter-2",
            name: "Menu Degustacyjne dla Dwóch Osób / Tasting menu for two",
            description:
              "Adana Kebap 1/2, Lamb Koftas 1/2, Shish Joojeh Chicken, Shish Taouk Chicken, Sauces: Basma, Zhoug, Toum, Amba, Harissa, Arabic Yogurt Relish, 2xPita, Rice, Fries With Sumac, Mixed Pickles",
            price: "219 zł",
            image: "/images/menu/meat-platter-for-two-new.jpeg",
            allergens: [1, 3, 7, 8, 10, 11, 12],
            notAvailableOnline: true,
          },
          {
            id: "meat-platter-4",
            name: "Menu Degustacyjne dla Czterech Osób / Tasting menu for four",
            description:
              "Adana Kebap, Lamb Koftas, Shish Joojeh Chicken, Shish Taouk Chicken, Chicken Shish Shawarma, Sauces: Basma, Zhoug, Toum, Amba, Harissa, Arabic Yogurt Relish, 4xPita, Rice, Fries With Sumac, Mixed Pickles",
            price: "399 zł",
            image: "/images/menu/meat-platter-for-four-new.jpeg",
            allergens: [1, 3, 7, 8, 10, 11, 12],
            notAvailableOnline: true,
          },
        ],
      },
      {
        categoryName: "Vege Grill",
        items: [
          {
            id: "grilled-aubergine",
            name: "Grillowany Bakłażan / Grilled aubergine",
            description:
              "Grillowany bakłażan z labneh miętowym, sałatą, ogórkiem, pomidorem, czerwoną cebulą i prażoną ciecierzycą",
            price: "46 zł",
            image: "/images/menu/baklazan-danie.jpg",
            allergens: [7, 11],
          },
          {
            id: "cauliflower-labneh",
            name: "Grillowany Kalafior / Grilled cauliflower",
            description: "z labneh, melasą z granatów, pastą sezamową, orzechową dukkah, płatkami róży i granatem",
            price: "46 zł",
            image: "/images/menu/cauliflower-labneh.jpeg",
            allergens: [7, 8, 11],
          },
          {
            id: "grilled-halloumi",
            name: "Grillowane Halloumi / Grilled halloumi",
            description: "Z chutney morelowym, orzechową dukkah, kolendrą i sosem harissa",
            price: "49 zł",
            image: "/images/menu/halloumi-danie.jpg",
            allergens: [7, 8, 12],
          },
        ],
      },
      {
        categoryName: "Dla Dzieci",
        items: [
          {
            id: "explorer-plate",
            name: "Talerz Odkrywcy / Explorer's plate",
            description: "Nuggety z piersi kurczaka, frytki, tzatziki, labneh, ogórek, pomidor",
            price: "36 zł",
            image: "/images/menu/explorer-plate.jpg",
            allergens: [1, 3, 7],
          },
        ],
      },
    ],
  },
  {
    id: "salatki",
    sectionTitle: "Sałatki",
    categories: [
      {
        categoryName: "Sałatki",
        items: [
          {
            id: "fattoush",
            name: "Fattoush",
            description:
              "Ubijana feta, sałata rzymska, ogórek, pomidor, granat, cebula, natka pietruszki, zatar, sumak, oliwa, smażona pita",
            price: "39 zł",
            image: "/images/menu/fattoush-new.webp",
            allergens: [1, 7, 11],
          },
          {
            id: "greek-salad",
            name: "Sałatka Grecka / Greek Salad",
            description: "Ser feta, ogórek, pomidor, oliwki, cebula, papryka, oliwa, oregano",
            price: "45 zł",
            image: "/images/menu/salatka-grecka.jpg",
            allergens: [1, 7],
          },
          {
            id: "halloumi-salad",
            name: "Sałatka Z Halloumi / Halloumi Salad",
            description: "Halloumi, sałata, ogórek, pomidor, oliwki, natka pietruszki, kolendra, dresing miodowy",
            price: "49 zł",
            image: "/images/menu/salatka-halloumi.jpg",
            allergens: [1, 7],
          },
        ],
      },
    ],
  },
  {
    id: "desery",
    sectionTitle: "Desery",
    categories: [
      {
        categoryName: "Słodkości Bliskowschodnie",
        items: [
          {
            id: "baklava",
            name: "Baklava",
            description: "Layered Dessert Made With Phyllo Dough, Pistachios and Honey",
            price: "12 zł",
            image: "/images/menu/baklava-new.webp",
            allergens: [1, 8, 11],
          },
          {
            id: "labneh-cheesecake",
            name: "Sernik z Labneh / Labneh Cheesecake",
            description: "Sernik z labneh podawany z melasą z daktyli",
            price: "25 zł",
            image: "/images/menu/sernik-labneh.jpg",
            allergens: [7],
          },
          {
            id: "dubai-dream",
            name: "Dubajski Sen / Dubai Dream",
            description:
              "Ciasto czekoladowe podane na chrupiącym kataifi z gałką lodów pistacjowych i sosem czekoladowym",
            price: "29 zł",
            image: "/images/menu/dubai-dream.jpeg",
            allergens: [1, 3, 7, 8],
            notAvailableForDelivery: true,
          },
          {
            id: "creme-brulee-basma",
            name: "Crème Brûlée by BASMA / Creme Brulee by basma",
            description: "Autorska wersja klasycznego deseru",
            price: "35 zł",
            image: "/images/menu/creme-brulee.jpeg",
            allergens: [3, 7],
            notAvailableForDelivery: true,
          },
          {
            id: "halva-mousse",
            name: "Halva Mousse",
            description: "Layerred With Phyllo Dough, Served With Raspberry Sauce And Seasonal Fruit",
            price: "35 zł",
            image: "/images/menu/mus-chalwowy-new.webp",
            allergens: [1, 7, 8],
            notAvailableOnline: true,
          },
        ],
      },
    ],
  },
  {
    id: "dodatki",
    sectionTitle: "Dodatki i Sosy",
    categories: [
      {
        categoryName: "Dodatki",
        items: [
          {
            id: "pita",
            name: "Pita",
            description: "Świeżo wypiekana pita",
            price: "7 zł",
            image: "/images/menu/pita-bread-fresh.jpeg",
            allergens: [1],
          },
          {
            id: "mix-pikli-side",
            name: "Mix pikli / Mixed Pickles",
            description: "Chrupiące warzywa w aromatycznej zalewie octowej",
            price: "8 zł",
            image: "/images/menu/mixed-pickles-mezze.jpeg",
            allergens: [10],
          },
          {
            id: "basmati-rice",
            name: "Ryż Basmati / Basmati rice",
            description: "z przyprawami bliskiego wschodu",
            price: "12 zł",
            image: "/images/menu/ryz-basmati.jpg",
            allergens: [1],
          },
          {
            id: "sumac-fries",
            name: "Frytki z Sumakiem / French fries with sumac",
            description: "Chrupiące frytki z aromatycznym sumakiem",
            price: "14 zł",
            image: "/images/menu/sumac-fries.jpeg",
            allergens: [1],
          },
          {
            id: "arabic-salad",
            name: "Sałatka Arabska / Arabic Salad",
            description: "Świeże warzywa z miętą, cytryną i oliwą",
            price: "12 zł",
            image: "/images/menu/arabic-salad.jpeg",
            allergens: [],
          },
          {
            id: "ayran",
            name: "Ayran",
            description: "Orzeźwiający napój jogurtowy domowej roboty",
            price: "8 zł",
            image: "/images/menu/ayran-fresh.jpeg",
            allergens: [7],
            notAvailableOnline: true,
          },
        ],
      },
      {
        categoryName: "Sosy",
        items: [
          {
            id: "toum",
            name: "Toum",
            description: "Kremowy sos czosnkowy",
            price: "5 zł",
            image: "/images/menu/toum-sauce.jpeg",
            allergens: [3],
          },
          {
            id: "arabic-yogurt-relish",
            name: "Arabic Yogurt Relish / Arabic yougurt relish",
            description: "Yogurt Sauce With Chopped Vegetables And Sumac",
            price: "5 zł",
            image: "/images/menu/arabic-jogurt-relish-new.webp",
            allergens: [7],
          },
          {
            id: "harissa",
            name: "Harissa",
            description: "Ostra pasta z chili",
            price: "5 zł",
            image: "/images/menu/harissa-sauce.jpeg",
            allergens: [],
          },
          {
            id: "zhoug",
            name: "Zhoug",
            description: "Zielony sos z ziół i chili",
            price: "5 zł",
            image: "/images/menu/zhoug-sauce.jpeg",
            allergens: [],
          },
          {
            id: "basma-sauce",
            name: "Basma",
            description: "Autorski sos Basma",
            price: "5 zł",
            image: "/images/menu/Sos BASMA.JPG",
            allergens: [3],
          },
          {
            id: "amba",
            name: "Amba",
            description: "Sweet-and-Sour Mango Sauce With Spicy Notes",
            price: "5 zł",
            image: "/images/menu/amba-new.webp",
            allergens: [],
          },
        ],
      },
    ],
  },
  {
    id: "napoje",
    sectionTitle: "Napoje",
    categories: [
      {
        categoryName: "Kawa i Herbata",
        items: [
          {
            id: "arabic-tea",
            name: "Herbata Arabska z Kardamonem / Arabic tea with cardamom",
            description: "Aromatyczna herbata z tradycyjnymi przyprawami",
            price: "7 zł",
            image: "/images/menu/herbata-arabska.jpg",
            allergens: [],
            notAvailableOnline: true,
          },
          {
            id: "espresso",
            name: "Espresso",
            description: "Klasyczne espresso",
            price: "8 zł",
            image: "/images/menu/espresso.jpg",
            allergens: [],
            notAvailableOnline: true,
          },
          {
            id: "espresso-doppio",
            name: "Espresso Doppio / Espresso doppio",
            description: "Podwójne espresso",
            price: "10 zł",
            image: "/images/menu/espresso-doppio.jpg",
            allergens: [],
            notAvailableOnline: true,
          },
          {
            id: "americano",
            name: "Americano",
            description: "Espresso z gorącą wodą",
            price: "10 zł",
            image: "/images/menu/americano.jpg",
            allergens: [],
            notAvailableOnline: true,
          },
          {
            id: "coffee-milk",
            name: "Kawa z Mlekiem / Coffee with milk",
            description: "Klasyczna kawa z mlekiem",
            price: "12 zł",
            image: "/images/menu/kawa-z-mlekiem.jpg",
            allergens: [7],
            notAvailableOnline: true,
          },
          {
            id: "cappuccino",
            name: "Cappuccino",
            description: "Espresso z spienioną pianką mleczną",
            price: "13 zł",
            image: "/images/menu/cappuccino.jpg",
            allergens: [7],
            notAvailableOnline: true,
          },
          {
            id: "flat-white",
            name: "Flat White",
            description: "Espresso z mikrospienioną pianką",
            price: "15 zł",
            allergens: [7],
            notAvailableOnline: true,
          },
          {
            id: "caffe-latte",
            name: "Caffe Latte",
            description: "Espresso z dużą ilością mleka",
            price: "16 zł",
            image: "/images/menu/latte.jpg",
            allergens: [7],
            notAvailableOnline: true,
          },
          {
            id: "iced-coffee",
            name: "Kawa Mrożona / Iced coffee",
            description: "Orzeźwiająca kawa na lodzie",
            price: "16 zł",
            image: "/images/menu/kawa-mrozona.jpg",
            allergens: [7],
            notAvailableOnline: true,
          },
          {
            id: "tonic-espresso",
            name: "Tonic Espresso / Tonic espresso",
            description: "Espresso z tonikiem",
            price: "18 zł",
            image: "/images/menu/tonic-espresso.jpg",
            allergens: [],
            notAvailableOnline: true,
          },
        ],
      },
      {
        categoryName: "Napoje Zimne",
        items: [
          {
            id: "water",
            name: "Woda / Water",
            description: "Gazowana / niegazowana 0,3L",
            price: "5 zł",
            image: "/images/menu/woda-03l.jpg",
            allergens: [],
          },
          {
            id: "flavored-water",
            name: "Woda z Miętą i Cytryną / Water with mint and lemon",
            description: "Gazowana / niegazowana 0,9L",
            price: "10 zł",
            image: "/images/menu/woda-09l.jpg",
            allergens: [],
          },
          {
            id: "coca-cola",
            name: "Coca-Cola / Coca cola etc.",
            description: "0,25L",
            price: "12 zł",
            image: "/images/menu/coca-cola.jpg",
            allergens: [],
          },
          {
            id: "coca-cola-zero",
            name: "Coca-Cola Zero",
            description: "0,25L",
            price: "12 zł",
            image: "/images/menu/coca-cola-zero.jpg",
            allergens: [],
          },
          {
            id: "fanta",
            name: "Fanta",
            description: "0,25L",
            price: "12 zł",
            image: "/images/menu/fanta.jpg",
            allergens: [],
          },
          {
            id: "sprite",
            name: "Sprite",
            description: "0,25L",
            price: "12 zł",
            image: "/images/menu/sprite.png",
            allergens: [],
          },
          {
            id: "juice-small",
            name: "Sok / Juice  (0,3L)",
            description: "Pomarańczowy / grejpfrutowy / jabłkowy 0,3L",
            price: "8 zł",
            image: "/images/menu/sok-jablkowy.jpg",
            allergens: [],
          },
          {
            id: "juice-large",
            name: "Sok / Juice  (1l)",
            description: "Pomarańczowy / grejpfrutowy / mix 1L",
            price: "18 zł",
            allergens: [],
          },
          {
            id: "fresh-juice",
            name: "Sok Świeżo Wyciskany / Freshly squeezed juice ( 0,2L)",
            description: "Pomarańczowy / grejpfrutowy / mix 0,2L",
            price: "18 zł",
            image: "/images/menu/sok-swiezo-wyciskany.jpg",
            allergens: [],
          },
        ],
      },
      {
        categoryName: "Koktajle Bezalkoholowe / Mocktails",
        items: [
          {
            id: "jallab-lemonade",
            name: "Jallab Lemonade",
            description: "Jallab / prażone migdały / mięta / sok cytrynowy / woda gazowana",
            price: "18 zł",
            image: "/images/menu/jallab-lemonade.jpg",
            allergens: [8, 12],
            notAvailableOnline: true,
          },
          {
            id: "basma-sour-lemonade",
            name: "Basma Sour Lemonade",
            description: "Sok z granatu / woda różana / sok z cytryny / mięta",
            price: "18 zł",
            image: "/images/menu/basma-sour-lemonade.jpg",
            allergens: [1, 12],
            notAvailableOnline: true,
          },
          {
            id: "milk-dactyl",
            name: "Milk Dactyl",
            description: "Napój owsiany / jallab / kardamon / cynamon",
            price: "18 zł",
            image: "/images/menu/milk-dactyl.jpg",
            allergens: [1],
            notAvailableOnline: true,
          },
          {
            id: "hibiscus-shams",
            name: "Hibiskus Shams",
            description: "Hibiscus Syrup, Jallab, Elderberry Syrup, Sparkling Water",
            price: "18 zł",
            image: "/images/menu/hibiskus-shams-new.webp",
            allergens: [],
            notAvailableOnline: true,
          },
          {
            id: "juniper-groove",
            name: "Juniper Groove",
            description: "Juniper Syrup, Rosemary, Lemon Juice, Orange Blossom Water, Sugar Syrup",
            price: "22 zł",
            image: "/images/menu/juniper-groove-new.webp",
            allergens: [],
            notAvailableOnline: true,
          },
          {
            id: "orange-spritz-free",
            name: "Orange Spritz free",
            description: "Sprissetto / prosecco zero / woda gazowana / pomarańcza",
            price: "25 zł",
            image: "/images/menu/orange-spritz-free.jpg",
            allergens: [12],
            notAvailableOnline: true,
          },
          {
            id: "limoncello-free",
            name: "Limoncello free",
            description: "Limoncello zero / prosecco zero / woda gazowana",
            price: "25 zł",
            image: "/images/menu/limoncello-free.jpg",
            allergens: [12],
            notAvailableOnline: true,
          },
        ],
      },
    ],
  },
  {
    id: "alkohole",
    sectionTitle: "Alkohole",
    categories: [
      {
        categoryName: "Koktajle / Cocktails",
        items: [
          {
            id: "mojito",
            name: "Mojito",
            description: "Planteray dark / cukier trzcinowy / limonka / mięta / woda gazowana",
            price: "28 zł",
            image: "/images/menu/mojito.jpg",
            allergens: [12],
          },
          {
            id: "mango-frizz",
            name: "Mango Frizz",
            description: "Prosecco / syrop mango / woda z kwiatów pomarańczy / woda gazowana",
            price: "28 zł",
            image: "/images/menu/mango-frizz.jpg",
            allergens: [12],
          },
          {
            id: "ginger-girl",
            name: "Ginger Girl",
            description:
              "Whitley Neill gin London dry / woda z kwiatów pomarańczy / syrop waniliowy / sok z cytryny / imbir / woda gazowana",
            price: "28 zł",
            image: "/images/menu/ginger-girl.jpg",
            allergens: [12],
          },
          {
            id: "nour",
            name: "Nour",
            description: "Martini bianco / puree z gruszki / syrop waniliowy / kardamon",
            price: "28 zł",
            image: "/images/menu/nour.jpg",
            allergens: [12],
          },
          {
            id: "negroni",
            name: "Negroni",
            description: "Whitley Neill gin London dry / Martini rosso / Campari",
            price: "32 zł",
            image: "/images/menu/negroni.jpg",
            allergens: [12],
          },
          {
            id: "cherry-amore",
            name: "Cherry amore",
            description: "Amaretto, Cherry Puree, Vanilla Syrup, Lemon Juice, Angostura Coccoa",
            price: "32 zł",
            image: "/images/menu/cherry-a-more-new.webp",
            allergens: [12],
          },
          {
            id: "whisky-sour-basma",
            name: "Whisky sour by BASMA",
            description: "Bushmills original / syrop z granatu / białko / angostura / sok z cytryny",
            price: "32 zł",
            image: "/images/menu/whisky-sour-basma.jpg",
            allergens: [3, 12],
          },
          {
            id: "sweet-sahara",
            name: "Sweet Sahara",
            description:
              "Likier melon / puree marakuja / woda z kwiatów pomarańczy / sok z cytryny / syrop cukrowy / białko",
            price: "32 zł",
            image: "/images/menu/sweet-sahara.jpg",
            allergens: [3, 12],
          },
          {
            id: "basma-martini",
            name: "BASMA Martini",
            description: "Distil No.9 / puree lychee / sok z cytryny / syrop różany",
            price: "32 zł",
            image: "/images/menu/basma-martini.jpg",
            allergens: [12],
          },
          {
            id: "violet-queen",
            name: "Violet Quenn",
            description: "Whitley Neill London Dry Gin, Hibiscus Syrup. Lychee Puree, Grapefruit Juice, Sugar Syrup",
            price: "34 zł",
            image: "/images/menu/violet-queen-new.webp",
            allergens: [12],
          },
          {
            id: "pink-madar",
            name: "Pink Madar",
            description: "Passoa, Lychee Puree, Hibiscus Syrup, Pomegranate Syrup",
            price: "34 zł",
            image: "/images/menu/pink-madar-new.webp",
            allergens: [12],
          },
          {
            id: "aperol-spritz",
            name: "Aperol Spritz",
            description: "Aperol / prosecco / woda gazowana / pomarańcza",
            price: "34 zł",
            image: "/images/menu/aperol-spritz.jpg",
            allergens: [12],
          },
          {
            id: "porn-star-martini",
            name: "Porn Star Martini",
            description: "Distil No.9 / prosecco / puree marakuja / syrop waniliowy / sok z cytryny",
            price: "36 zł",
            image: "/images/menu/porn-star-martini.jpg",
            allergens: [1, 12],
          },
          {
            id: "oasis",
            name: "Oasis",
            description: "Orzeźwiający koktajl tropikalny z rumem, marakują i kokosem / Refreshing tropical cocktail with rum, passion fruit and coconut",
            price: "36 zł",
            image: "/images/menu/sweet-sahara.jpg",
            allergens: [12],
          },
        ],
      },
      {
        categoryName: "Piwo i Wino / Alcohols",
        items: [
          {
            id: "perla-export",
            name: "Perła Export ( bottle 0,5l)",
            description: "Butelkowe piwo Perła Export",
            price: "16 zł",
            allergens: [1],
          },
          {
            id: "craft-beer",
            name: "Craft Beer-Bottled",
            description: "Szeroki wybór piw kraftowych - zapytaj obsługę o aktualną ofertę",
            price: "21 zł",
            allergens: [1, 12],
          },
          {
            id: "wine-muscaris",
            name: "Majątek Drzewce Muscaris",
            description: "Glass (150 ml)",
            price: "32 zł",
            allergens: [12],
          },
          {
            id: "wine-johanniter",
            name: "Kazimierskie Wzgórza Johanniter",
            description: "Glass (150 ml)",
            price: "32 zł",
            allergens: [12],
          },
          {
            id: "house-wine-glass",
            name: "Wino Domowe - Kieliszek",
            description: "Wytrawne, białe/czerwone (150 ml)",
            price: "19 zł",
            image: "/images/menu/wino-biale.jpg",
            allergens: [12],
          },
          {
            id: "house-wine-carafe-small",
            name: "Wino Domowe - Karafka 0,5L",
            description: "Wytrawne, białe/czerwone",
            price: "49 zł",
            allergens: [12],
          },
          {
            id: "house-wine-carafe-large",
            name: "Wino Domowe - Karafka 1L",
            description: "Wytrawne, białe/czerwone",
            price: "79 zł",
            allergens: [12],
          },
          {
            id: "prosecco-glass",
            name: "Prosecco",
            description: "150 ml",
            price: "19 zł",
            image: "/images/menu/prosecco.jpg",
            allergens: [12],
          },
          {
            id: "prosecco-free-glass",
            name: "Prosecco Free",
            description: "Kieliszek (150 ml)",
            price: "19 zł",
            image: "/images/menu/prosecco.jpg",
            allergens: [],
          },
          {
            id: "bottled-wine",
            name: "Wino Butelkowe",
            description: "Posiadamy szeroki wybór win butelkowych. O aktualną ofertę zapytaj obsługę.",
            price: "od 79 zł",
            allergens: [12],
          },
        ],
      },
      {
        categoryName: "Alkohole Mocne (40ml)",
        items: [
          {
            id: "vodka-distil",
            name: "Wódka Nemiroff",
            description: "Premium wódka",
            price: "13 zł",
            allergens: [],
          },
          {
            id: "vodka-ostoya",
            name: "Wódka Ostoya",
            description: "Polska wódka premium",
            price: "16 zł",
            allergens: [],
          },
          {
            id: "whisky-bushmills",
            name: "Whisky Bushmills Original",
            description: "Irlandzka whisky",
            price: "18 zł",
            allergens: [],
          },
          {
            id: "whisky-glenmoray-12",
            name: "Whisky Glenmoray Single Malt 12 YO",
            description: "Szkocka whisky single malt",
            price: "22 zł",
            allergens: [],
          },
          {
            id: "whisky-glenmoray-15",
            name: "Whisky Glenmoray Single Malt 15 YO",
            description: "Szkocka whisky single malt",
            price: "29 zł",
            allergens: [],
          },
          {
            id: "whisky-nikka",
            name: "Nikka Coffey Grain Whisky",
            description: "Japońska whisky",
            price: "35 zł",
            allergens: [],
          },
          {
            id: "rum-planteray",
            name: "Rum Planteray Dark",
            description: "Ciemny rum",
            price: "20 zł",
            allergens: [],
          },
          {
            id: "rum-kraken",
            name: "Kraken Black Spiced",
            description: "Korzenny rum",
            price: "24 zł",
            allergens: [],
          },
          {
            id: "gin-whitley",
            name: "Gin Whitley Neill Distiller's Cut London Dry",
            description: "London Dry Gin",
            price: "18 zł",
            allergens: [],
          },
          {
            id: "gin-bombay",
            name: "Bombay Sapphire London Dry",
            description: "Premium London Dry Gin",
            price: "24 zł",
            allergens: [],
          },
          {
            id: "gin-drumshanbo",
            name: "Drumshanbo Gunpowder Irish Citrus",
            description: "Irlandzki gin z cytrusami",
            price: "29 zł",
            allergens: [],
          },
          {
            id: "tequila-silver",
            name: "Jose Cuervo Silver",
            description: "Srebrna tequila",
            price: "16 zł",
            allergens: [],
          },
          {
            id: "tequila-reposado",
            name: "Jose Cuervo Reposado",
            description: "Leżakowana tequila",
            price: "16 zł",
            allergens: [],
          },
          {
            id: "cognac-gautier",
            name: "Cognac Gautier",
            description: "Francuski koniak",
            price: "26 zł",
            allergens: [],
          },
          {
            id: "cognac-hennessy",
            name: "Hennessy VS",
            description: "Premium koniak",
            price: "39 zł",
            allergens: [],
          },
        ],
      },
    ],
  }
];

export const specialOccasionsData: MenuCategory = {
  id: "specjalne-okazje",
  sectionTitle: "Menu na Specjalne Okazje",
  isPackageSection: true,
  packages: [
    {
      packageId: "party-box",
      packageName: "PARTY BOX (dla 4 osób)",
      packagePrice: "299 zł",
      packageImage: "/images/menu/party-box.jpg",
      categories: [
        {
          categoryName: "Zawartość Party Boxa",
          items: [
            { id: "pb-labneh-basma", name: "Labneh by BASMA", description: "", price: "", allergens: [7, 11] },
            { id: "pb-tabbouleh", name: "Tabbouleh", description: "", price: "", allergens: [1, 10] },
            { id: "pb-hummus", name: "Hummus", description: "", price: "", allergens: [11] },
            { id: "pb-olives", name: "Oliwki marynowane", description: "", price: "", allergens: [11] },
            { id: "pb-pickles", name: "Pikle", description: "", price: "", allergens: [10] },
            { id: "pb-hummus-bean", name: "Hummus z fasoli", description: "", price: "", allergens: [1, 11] },
            { id: "pb-tabbouleh-basma", name: "Tabbouleh by BASMA", description: "", price: "", allergens: [1, 8, 10] },
            { id: "pb-baba-ghanoush", name: "Baba Ghanoush", description: "", price: "", allergens: [7, 11] },
            { id: "pb-muhammara", name: "Muhammara", description: "", price: "", allergens: [8] },
            { id: "pb-fattoush", name: "Sałatka fattoush", description: "", price: "", allergens: [1, 7, 11] },
            { id: "pb-wrap-falafel", name: "Mini Wrapy z falafelem 4x", description: "", price: "", allergens: [1, 11] },
            { id: "pb-wrap-eggplant", name: "Mini Wrapy z bakłażanem 4x", description: "", price: "", allergens: [1, 11] },
            { id: "pb-simit-chicken", name: "Simit z kurczakiem taouk 4x", description: "", price: "", allergens: [1, 3, 7, 10, 11] },
            { id: "pb-bread-sticks", name: "Paluchy chlebowe 4x", description: "", price: "", allergens: [1] },
          ],
        },
      ],
    },
    {
      packageId: "package-1",
      packageName: "MEZZE & GRILL - PAKIET 1",
      packagePrice: "159 zł / osoba",
      packageDescription: "Cena: 159 ZŁ / OSOBA",
      categories: [
        {
          categoryName: "Przystawki (Serwowane z pitą, do wyboru 5)",
          items: [
            { id: "p1-hummus", name: "HUMMUS", description: "", price: "" },
            { id: "p1-tzatziki", name: "TZATZIKI", description: "", price: "" },
            { id: "p1-labneh", name: "LABNEH", description: "", price: "" },
            { id: "p1-labneh-sweet", name: "LABNEH NA SŁODKO", description: "", price: "" },
            { id: "p1-hummus-white-bean", name: "HUMMUS Z BIAŁEJ FASOLI", description: "", price: "" },
            { id: "p1-olives", name: "MARYNOWANE OLIWKI", description: "", price: "" },
            { id: "p1-tabbouleh", name: "TABBOULEH", description: "", price: "" },
            { id: "p1-grilled-pepper", name: "GRILLOWANA PAPRYKA NA LABNEH", description: "", price: "" },
            { id: "p1-labneh-basma", name: "LABNEH BY BASMA", description: "", price: "" },
            { id: "p1-muhammara", name: "MUHAMMARA", description: "", price: "" },
            { id: "p1-baba-ghanoush", name: "BABA GHANOUSH", description: "", price: "" },
            { id: "p1-whipped-feta", name: "UBIJANA FETA", description: "", price: "" },
          ],
        },
        {
          categoryName: "Zupa (Do wyboru 1)",
          items: [
            { id: "p1-soup-header-meat", name: "Mięsne:", description: "", price: "" },
            { id: "p1-shorbat-kibbeh", name: "SHORBAT KIBBEH", description: "Rosół wołowy z pulpecikami", price: "" },
            { id: "p1-harira", name: "HARIRA", description: "Zupa z wołowiną, cieciorką i pomidorami", price: "" },
            { id: "p1-hafira", name: "HAFIRA", description: "Arabska zupa z kurczakiem i ciecierzycą", price: "" },
            { id: "p1-soup-header-veg", name: "Wegetariańskie:", description: "", price: "" },
            { id: "p1-pumpkin-cream", name: "KREM DYNIOWY Z TAHINI I HARISSĄ", description: "", price: "" },
            { id: "p1-sweet-potato-cream", name: "KREM Z BATATA", description: "", price: "" },
          ],
        },
        {
          categoryName: "Dania (Do wyboru 1 mięsne lub 1 wegetariańskie na osobę)",
          items: [
            { id: "p1-main-header-meat", name: "Mięsne:", description: "", price: "" },
            { id: "p1-adana-kebab", name: "ADANA KEBAB", description: "Serwowany na picie, z ryżem, sałatką arabską i labneh", price: "" },
            { id: "p1-chicken-touk", name: "KURCZAK TOUK Z HARISSĄ", description: "Podawany z ryżem basmati z pomidorami lub frytkami z sumakiem, cytryną kiszoną oraz sałatką arabską lub mixem pikli", price: "" },
            { id: "p1-chicken-joojeh", name: "KURCZAK SHISH JOOJEH", description: "Podawany z ryżem basmati z pomidorami lub frytkami z sumakiem oraz z sałatką arabską lub mixem pikli", price: "" },
            { id: "p1-main-header-veg", name: "Wegetariańskie:", description: "", price: "" },
            { id: "p1-cauliflower", name: "KALAFIOR PANIEROWANY", description: "Polany sosem tahini i harissa, podawany z bulgurem z warzywami oraz piklowanym kalafiorem", price: "" },
            { id: "p1-grilled-aubergine", name: "GRILLOWANY BAKŁAŻAN", description: "Serwowany na hummusie z fasoli", price: "" },
          ],
        },
        {
          categoryName: "Deser",
          items: [
            { id: "p1-dubai-dream", name: "DUBAJSKI SEN", description: "Ciasto czekoladowe podane na chrupiącym kataifi, z gałką lodów pistacjowych i sosem czekoladowym", price: "" },
            { id: "p1-cheesecake", name: "SERNIK Z LABNEH", description: "Serwowany z melasą daktylową", price: "" },
            { id: "p1-date-cake", name: "CIASTO DAKTYLOWE", description: "Podawane ze śmietanką tahini, lodami waniliowymi i chipsem z ciasta filo", price: "" },
            { id: "p1-ice-cream-duo", name: "LODY DUO (PISTACJA, WANILIA)", description: "W polewie z belgijskiej czekolady, z konfiturą z pomarańczy i ciastem kataifi", price: "" },
          ],
        },
      ],
    },
    {
      packageId: "package-2",
      packageName: "MEZZE & GRILL - PAKIET 2",
      packagePrice: "299 zł / osoba",
      packageDescription: "Cena: 299 ZŁ / OSOBA",
      categories: [
        {
          categoryName: "Przystawki (Serwowane z pitą, do wyboru 7)",
          items: [
            { id: "p2-hummus", name: "HUMMUS", description: "", price: "" },
            { id: "p2-tzatziki", name: "TZATZIKI", description: "", price: "" },
            { id: "p2-labneh", name: "LABNEH", description: "", price: "" },
            { id: "p2-labneh-sweet", name: "LABNEH NA SŁODKO", description: "", price: "" },
            { id: "p2-hummus-white-bean", name: "HUMMUS Z BIAŁEJ FASOLI", description: "", price: "" },
            { id: "p2-olives", name: "MARYNOWANE OLIWKI", description: "", price: "" },
            { id: "p2-tabbouleh", name: "TABBOULEH", description: "", price: "" },
            { id: "p2-grilled-pepper", name: "GRILLOWANA PAPRYKA NA LABNEH", description: "", price: "" },
            { id: "p2-labneh-basma", name: "LABNEH BY BASMA", description: "", price: "" },
            { id: "p2-muhammara", name: "MUHAMMARA", description: "", price: "" },
            { id: "p2-baba-ghanoush", name: "BABA GHANOUSH", description: "", price: "" },
            { id: "p2-whipped-feta", name: "UBIJANA FETA", description: "", price: "" },
            { id: "p2-pita", name: "PITA", description: "", price: "" },
          ],
        },
        {
          categoryName: "Zupa (Do wyboru 1)",
          items: [
            { id: "p2-soup-header-meat", name: "Mięsne:", description: "", price: "" },
            { id: "p2-shorbat-kibbeh", name: "SHORBAT KIBBEH", description: "Rosół wołowy z pulpecikami", price: "" },
            { id: "p2-harira", name: "HARIRA", description: "Zupa z wołowiną, cieciorką i pomidorami", price: "" },
            { id: "p2-hafira", name: "HAFIRA", description: "Arabska zupa z kurczakiem i ciecierzycą", price: "" },
            { id: "p2-soup-header-veg", name: "Wegetariańskie:", description: "", price: "" },
            { id: "p2-pumpkin-cream", name: "KREM DYNIOWY Z TAHINI I HARISSĄ", description: "", price: "" },
            { id: "p2-sweet-potato-cream", name: "KREM Z BATATA", description: "", price: "" },
          ],
        },
        {
          categoryName: "Przystawka Serwowana (Do wyboru 1 mięsna lub 1 wegetariańska na osobę)",
          items: [
            { id: "p2-served-header-meat", name: "Mięsna:", description: "", price: "" },
            { id: "p2-carpaccio-beef", name: "CARPACCIO WOŁOWE", description: "Podawane z labneh, orzeszkami pini, okrą, oliwą ziołową i smażoną pitą", price: "" },
            { id: "p2-beef-tartare", name: "TATAR Z POLĘDWICY WOŁOWEJ", description: "Serwowany z żółtkiem, cebulą, piklowanym ogórkiem, skórką z cytryny i pomarańczy, labneh oraz smażoną pitą", price: "" },
            { id: "p2-served-header-veg", name: "Wegetariańska:", description: "", price: "" },
            { id: "p2-carpaccio-beet", name: "CARPACCIO Z PIECZONEGO W SOLI BURAKA", description: "Podawane z labneh, orzechową dukkah, melasą z granatu, miodem i ziołową sałatką", price: "" },
            { id: "p2-aubergine-rolls", name: "ROLADKI Z GRILLOWANEGO BAKŁAŻANA I RUKOLA", description: "Serwowane z labneh orzechowym z czosnkiem confit", price: "" },
          ],
        },
        {
          categoryName: "Dania (Do wyboru 1 mięsne lub 1 wegetariańskie na osobę)",
          items: [
            { id: "p2-main-header-meat", name: "Mięsne:", description: "", price: "" },
            { id: "p2-lamb-comber", name: "COMBER JAGNIĘCY", description: "Serwowany z ryżem oraz sałatką ziołową z fenkułem i granatem", price: "" },
            { id: "p2-beef-steak", name: "STEK Z POLĘDWICY WOŁOWEJ", description: "Podawany z ziemniakami latkes, szaszłykiem warzywnym, labneh i sosem zoug", price: "" },
            { id: "p2-meat-trio", name: "TRIO MIĘS (ADANA KEBAB, KOFTA JAGNIĘCA, KURCZAK)", description: "Podawane z pieczonym ziemniakiem z zatarem i sumakiem, oraz piklowaną kapustą i ogórkiem", price: "" },
            { id: "p2-main-header-veg", name: "Wegetariańskie:", description: "", price: "" },
            { id: "p2-cauliflower", name: "KALAFIOR PANIEROWANY", description: "Polany sosem tahini i harissa, podawany z bulgurem z warzywami oraz piklowanym kalafiorem", price: "" },
            { id: "p2-grilled-aubergine", name: "GRILLOWANY BAKŁAŻAN", description: "Serwowany na hummusie z fasoli", price: "" },
          ],
        },
        {
          categoryName: "Deser",
          items: [
            { id: "p2-dubai-dream", name: "DUBAJSKI SEN", description: "Ciasto czekoladowe podane na chrupiącym kataifi, z gałką lodów pistacjowych i sosem czekoladowym", price: "" },
            { id: "p2-cheesecake", name: "SERNIK Z LABNEH", description: "Serwowany z melasą daktylową", price: "" },
            { id: "p2-date-cake", name: "CIASTO DAKTYLOWE", description: "Podawane ze śmietanką tahini, lodami waniliowymi i chipsem z ciasta filo", price: "" },
            { id: "p2-ice-cream-duo", name: "LODY DUO (PISTACJA, WANILIA)", description: "W polewie z belgijskiej czekolady, z konfiturą z pomarańczy i ciastem kataifi", price: "" },
          ],
        },
      ],
    },
  ],
  categories: [
    {
      categoryName: "Napoje - Opcjonalny Pakiet Wybranych Napojów Bezalkoholowych",
      items: [
        { id: "drinks-soft", name: "Pakiet Napojów Bezalkoholowych", description: "Woda gazowana/niegazowana z miętą i cytryną - bez limitu • Lemoniada homemade - bez limitu • Cola 1L / Sprite 1L - bez limitu • Kawa / Herbata - bez limitu", price: "49 zł / osoba" },
      ],
    },
    {
      categoryName: "Napoje - Opcjonalny Pakiet Soft Open Bar",
      items: [
        { id: "drinks-soft-bar", name: "Pakiet Soft Open Bar", description: "Woda gazowana/niegazowana z miętą i cytryną - bez limitu • Lemoniada homemade - bez limitu • Cola 1L / Sprite 1L - bez limitu • Kawa / Herbata - bez limitu • Piwo rzemieślnicze - bez limitu • Wino domu białe / czerwone w karafkach - bez limitu", price: "139 zł / osoba" },
      ],
    },
    {
      categoryName: "Napoje - Opcjonalny Pakiet Open Bar",
      items: [
        { id: "drinks-open-bar", name: "Pakiet Open Bar", description: "Woda gazowana/niegazowana z miętą i cytryną - bez limitu • Lemoniada homemade - bez limitu • Cola 1L / Sprite 1L - bez limitu • Kawa / Herbata - bez limitu • Wszystkie alkohole - bez limitu", price: "249 zł / osoba" },
      ],
    },
    {
      categoryName: "Uwagi",
      items: [
        { id: "notes-deposit", name: "Zaliczka", description: "Warunkiem potwierdzenia rezerwacji jest wpłacenie zaliczki w kwocie 50% wartości zamówienia", price: "" },
        { id: "notes-service", name: "Opłata Serwisowa", description: "Do grup od 10 osób doliczamy opłatę za serwis w wysokości 10 zł/os netto (plus VAT 23%)", price: "" },
      ],
    },
  ],
}

export const allergenMap: { [key: number]: string } = {
  1: "Gluten",
  2: "Skorupiaki",
  3: "Jaja",
  4: "Ryby",
  5: "Orzeszki ziemne",
  6: "Soja",
  7: "Mleko",
  8: "Orzechy",
  9: "Seler",
  10: "Gorczyca",
  11: "Sezam",
  12: "Dwutlenek siarki",
  13: "Łubin",
  14: "Mięczaki",
}

// Helper function to get allergen names
export const getAllergenNames = (allergenNumbers: number[]): string[] => {
  return allergenNumbers.map((num) => allergenMap[num]).filter(Boolean)
}
