/**
 * Alphabetically sorted list of streets in Lublin and surrounding areas.
 * Used in the checkout page for the delivery address dropdown.
 */
export const LUBLIN_STREETS: string[] = [
    "1 Maja",
    "3 Maja",
    "Abramowice Prywatne",
    "Abramowicka",
    "Agronomiczna",
    "Al. Andersa",
    "Al. Długosza",
    "Al. Kompozytorów Polskich",
    "Al. Kraśnicka",
    "Al. Piłsudskiego",
    "Al. Racławickie",
    "Al. Sikorskiego",
    "Al. Smorawińskiego",
    "Al. Solidarności",
    "Al. Spółdzielczości Pracy",
    "Al. Tadeusza Mazowieckiego",
    "Al. Tysiąclecia",
    "Al. Unii Lubelskiej",
    "Al. Warszawska",
    "Al. Witosa",
    "Al. Zygmuntowskie",
    "Armii Krajowej",
    "Barak",
    "Biernackiego",
    "Biskupie Kolonia",
    "Bohaterów M. Cassino",
    "Bohaterów Monte Cassino",
    "Braci Krausse",
    "Brzegowa",
    "Budowlana",
    "Bursaki",
    "Bystrzyca",
    "Charlęż-Kolonia",
    "Chemiczna",
    "Chodźki",
    "Choiny",
    "Chopina",
    "Ciecierzyn",
    "Cienista",
    "Cukrownicza",
    "Cynamonowa",
    "Czechowska",
    "Czerniejów",
    "Ćmiłów",
    "Daszyńskiego",
    "Dąbrowica",
    "Dekutowskiego",
    "Dębówka",
    "Diamentowa",
    "Długa",
    "Długie",
    "Do Dysa",
    "Dobrzańskiego",
    "Dolna 3 Maja",
    "Dominów",
    "Doświadczalna",
    "Dożynkowa",
    "Droga Męczenników Majdanka",
    "Dworcowa",
    "Dys",
    "Dywizjonu 303",
    "Elizówka",
    "Elsnera",
    "Fabryczna",
    "Felin",
    "Fijałkowskiego",
    "Filaretów",
    "Franciszków",
    "Franczaka \"Lalka\"",
    "Gen. Ducha",
    "Gębali",
    "Gęsia",
    "Głęboka",
    "Główna",
    "Głuska",
    "Głuszczyzna",
    "Gospodarcza",
    "Grabskiego",
    "Granitowa",
    "Grenadierów",
    "Grygowej",
    "Helenów",
    "Herberta",
    "Hutnicza",
    "Inżynierska",
    "Jabłonna-Majątek",
    "Jacków",
    "Jaczewskiego",
    "Jakubowice Konińskie",
    "Jakubowice Konińskie-Kolonia",
    "Jana Pawła II",
    "Janowska",
    "Jastków",
    "Jawidz",
    "Judyma",
    "Kalinowszczyzna",
    "Kalinówka",
    "Kasprowicza",
    "Kawka",
    "Kłopotowskiego",
    "Kolonia Pliszczyn",
    "Kolonia Snopków",
    "Kolonia Świdnik Mały",
    "Koncertowa",
    "Konopnica",
    "Koryznowej",
    "Kosmowskiej",
    "Kozubszczyzna",
    "Krakowskie Przedmieście",
    "Krańcowa",
    "Krasienin",
    "Krasienin-Kolonia",
    "Krępiecka",
    "Krężnica Jara",
    "Krężnicka",
    "Krochmalna",
    "Królewska",
    "Kukułcza",
    "Kunickiego",
    "Kupiecka",
    "Leszczyńskiego",
    "Lędzian",
    "Lipińskiego",
    "Lipowa",
    "Lubartowska",
    "Lubelskiego Lipca '80",
    "Lubelskiego Lipca 80",
    "Lwowska",
    "Łagiewniki",
    "Łęczyńska",
    "Łysaków",
    "Majdan Krasieniński",
    "Marynin",
    "Mełgiew",
    "Mełgiewska",
    "Metalurgiczna",
    "Mętów",
    "Mickiewicza",
    "Młyńska",
    "Moritza",
    "Morwowa",
    "Mościckiego",
    "Motycz",
    "Motycz Leśny",
    "Muzyczna",
    "Nadbystrzycka",
    "Nałęczowska",
    "Nałkowskich",
    "Narutowicza",
    "Nasutowska",
    "Nasutów",
    "Niepodległości",
    "Nowy Świat",
    "Obywatelska",
    "Okopowa",
    "Orkana",
    "Orzechowa",
    "Osmolice Pierwsze",
    "Osmolicka",
    "Pancerniaków",
    "Panieńszczyzna",
    "Parysa",
    "Pasieczna",
    "Pawia",
    "Piaskowa",
    "Piotrawin",
    "Piotrowice",
    "Plewińskiego",
    "Pliszczyn",
    "Pliszczyńska",
    "Płouszowice-Kolonia",
    "Podzamcze",
    "Poligonowa",
    "Poniatowskiego",
    "Ponikwoda",
    "Popiełuszki",
    "Pólko",
    "Północna",
    "Prawiedniki",
    "Prusa",
    "Pszczela",
    "Radawczyk Drugi",
    "Radawiec Duży",
    "Radawiec Mały",
    "Rapackiego",
    "Rataja",
    "Romera",
    "Roztocze",
    "Rudnik",
    "Rusałka",
    "Ruska",
    "Sławin",
    "Sławinkowska",
    "Smoluchowskiego",
    "Smugi",
    "Snopków",
    "Sobianowice",
    "Sowińskiego",
    "Spiczyn",
    "Spiessa",
    "Stadionowa",
    "Stary Gaj",
    "Stasin",
    "Stefczyka",
    "Strzembosza",
    "Szeligowskiego",
    "Szerokie",
    "Ślężan",
    "Świdniczek",
    "Świdnik",
    "Świdnik Duży",
    "Świdnik Mały",
    "Tomaszowice-Kolonia",
    "Turka",
    "Turystyczna",
    "Unicka",
    "Uniszowice",
    "Vetterów",
    "Walecznych",
    "Wądolna",
    "Węglarza",
    "Wileńska",
    "Willowa",
    "Wodopojna",
    "Wojciechowska",
    "Wojtasa",
    "Wolska",
    "Wólka",
    "Wrotkowska",
    "Wróbla",
    "Wygodna",
    "Wyścigowa",
    "Wyzwolenia",
    "Zamojska",
    "Zana",
    "Zawieprzyce",
    "Zbożowa",
    "Zelwerowicza",
    "Zemborzyce Dolne",
    "Zemborzyce Podleśne",
    "Zemborzyce Tereszyńskie",
    "Zemborzyce Wojciechowskie",
    "Zemborzycka",
    "Zesłańców Sybiru",
    "Zorza",
    "Związkowa",
    "Zwycięska",
    "Żeglarska",
]
