/**
 * Alphabetically sorted list of streets in Lublin.
 * Used in the checkout page for the delivery address dropdown.
 */
export const LUBLIN_STREETS: string[] = [
    "1 Maja",
    "3 Maja",
    "Abramowicka",
    "Adama Mickiewicza",
    "Al. Józefa Piłsudskiego",
    "Al. Kraśnicka",
    "Al. Racławickie",
    "Al. Solidarności",
    "Al. Spółdzielczości Pracy",
    "Al. Tysiąclecia",
    "Al. Warszawska",
    "Al. Wincentego Witosa",
    "Al. Zygmuntowskie",
    "Armii Krajowej",
    "Baśniowa",
    "Bazylianówka",
    "Bema",
    "Berylowa",
    "Biernackiego",
    "Boczna Lubomelskiej",
    "Bohaterów Monte Cassino",
    "Bolesława Chrobrego",
    "Bolesława Prusa",
    "Brata Alberta",
    "Braci Wieniawskich",
    "Bronowicka",
    "Brygady",
    "Bursztynowa",
    "Cegielniana",
    "Chmielna",
    "Chodźki",
    "Choiny",
    "Cicha",
    "Czapskiego",
    "Czarneckiego",
    "Czechowska",
    "Czerska",
    "Czerwonego Krzyża",
    "Czuby Południowe",
    "Dębowa",
    "Diamentowa",
    "Długa",
    "Długosza",
    "Doktora Męczenników Majdanka",
    "Dolna 3 Maja",
    "Dolna Panny Marii",
    "Dominikańska",
    "Droga Męczenników Majdanka",
    "Dzierżawna",
    "Elsnera",
    "Farbiarskiej",
    "Fabryczna",
    "Filaretów",
    "Firlejowska",
    "Floriańska",
    "Franciszka Kleeberga",
    "Fredry",
    "Furmańska",
    "Garbarska",
    "Gęsia",
    "Głęboka",
    "Głowackiego",
    "Godebskiego",
    "Gospodarcza",
    "Graniczna",
    "Grażyny",
    "Grodzka",
    "Grottgera",
    "Grudzicka",
    "Grunwaldzka",
    "Handlowa",
    "Harnasie",
    "Herbowa",
    "Hirszfelda",
    "Hutnicza",
    "Inwalidzka",
    "Jana Długosza",
    "Jana Kasprowicza",
    "Jana Pawła II",
    "Jana Sawy",
    "Janowska",
    "Jaskółcza",
    "Jaśminowa",
    "Jemiołowa",
    "Jesienna",
    "Jezuicka",
    "Józefa Franczaka \"Lalka\"",
    "Kalina",
    "Kalinowa",
    "Kalinowszczyzna",
    "Kameralna",
    "Karłowicza",
    "Kazimierza Wielkiego",
    "Kędzierskiego",
    "Klemensa Junoszy",
    "Klonowa",
    "Kminkowa",
    "Kocia",
    "Kołłątaja",
    "Konopnickiej",
    "Kopernika",
    "Koralowa",
    "Kosmonautów",
    "Kościuszki",
    "Kowalska",
    "Krakowskie Przedmieście",
    "Krasińskiego",
    "Krochmalna",
    "Królewska",
    "Krótka",
    "Kręta",
    "Kunickiego",
    "Langiewicza",
    "Legionowa",
    "Leśna",
    "Lipowa",
    "Liszta",
    "Lubartowska",
    "Lubelskiego Lipca '80",
    "Lubomelska",
    "Lwowska",
    "Łęczyńska",
    "Łopuskiego",
    "Łowicka",
    "Magnoliowa",
    "Marii Curie-Skłodowskiej",
    "Mełgiewska",
    "Metalurgiczna",
    "Mętna",
    "Mieczysława Karłowicza",
    "Miernicza",
    "Mikołaja Reja",
    "Młyńska",
    "Morwa",
    "Muzyczna",
    "Nadbystrzyca",
    "Nadbystrzycka",
    "Nadrzeczna",
    "Narutowicza",
    "Nałęczowska",
    "Nałkowskich",
    "Niecała",
    "Niepodległości",
    "Nowa",
    "Nowomiejska",
    "Obywatelska",
    "Ochotnicza",
    "Ogrodowa",
    "Okopowa",
    "Olszewskiego",
    "Orkana",
    "Orłosia",
    "Owocowa",
    "Paderewskiego",
    "Pana Tadeusza",
    "Parkowa",
    "Peowiaków",
    "Piaskowa",
    "Piłsudskiego",
    "Plac Bychawski",
    "Plac Litewski",
    "Plac Łokietka",
    "Plac Wolności",
    "Plaża",
    "Podwale",
    "Poligonowa",
    "Polna",
    "Ponikwoda",
    "Poniatowskiego",
    "Poziomkowa",
    "Probostwo",
    "Prymasa Stefana Wyszyńskiego",
    "Przybyłów",
    "Przyjaźni",
    "Puławska",
    "Racławicka",
    "Radości",
    "Radziwiłłowska",
    "Ratuszowa",
    "Relaksowa",
    "Romera",
    "Rozmarynowa",
    "Ruska",
    "Rymarska",
    "Rynek",
    "Sandomierska",
    "Sasankowa",
    "Sienna",
    "Sieroce",
    "Skierki",
    "Skłodowskiej",
    "Słoneczna",
    "Słowackiego",
    "Słowicza",
    "Sławinkowska",
    "Spadochroniarzy",
    "Spokojna",
    "Stadionowa",
    "Staszica",
    "Stare Miasto",
    "Stefana Batorego",
    "Strażacka",
    "Sulisławicka",
    "Szafirowa",
    "Szaserów",
    "Szczebrzyska",
    "Szczęśliwa",
    "Szkolna",
    "Szpitalna",
    "Ślężańska",
    "Ślusarska",
    "Świętego Ducha",
    "Tatarska",
    "Towarowa",
    "Tumidajskiego",
    "Turystyczna",
    "Tylna",
    "Unicka",
    "Urzędowska",
    "Walecznych",
    "Wallenroda",
    "Watykańska",
    "Weteranów",
    "Wielka",
    "Wierzbowa",
    "Willowa",
    "Wioślarska",
    "Wojciechowska",
    "Wolska",
    "Wspólna",
    "Wyzwolenia",
    "Zamkowa",
    "Zamojska",
    "Zawieprzycka",
    "Zbożowa",
    "Zdrowa",
    "Zemborzyckа",
    "Zielona",
    "Złota",
    "Złotego",
    "Związkowa",
    "Żelazna",
    "Żołnierzy Niepodległej",
    "Żurawia",
    "Żwirki i Wigury",
]
